"""
3D ULPIN - Web Data Preparation Pipeline

Converts the validated synthetic cadastral dataset into
frontend-consumable GeoJSON, 3D model copies, and JSON
manifests.

Pipeline:

GIS source data
    ↓
Validated cadastral objects
    ↓
Web export
    ↓
GeoJSON + OBJ + metadata
    ↓
Cesium / React frontend
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

import geopandas as gpd


# ============================================================
# CONFIGURATION
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[3]

STUDY_AREA_DIR = (
    PROJECT_ROOT
    / "data"
    / "synthetic"
    / "study_area"
)

OUTPUT_DIR = (
    PROJECT_ROOT
    / "data"
    / "outputs"
    / "web"
)

GEOJSON_DIR = OUTPUT_DIR / "geojson"
MODEL_DIR = OUTPUT_DIR / "3d"

EXPECTED_CRS = "EPSG:32646"


# Source files
STUDY_AREA_FILE = STUDY_AREA_DIR / "study_area.geojson"
PARCELS_FILE = STUDY_AREA_DIR / "parcels.geojson"
BUILDINGS_FILE = STUDY_AREA_DIR / "buildings.geojson"
FLOORS_FILE = STUDY_AREA_DIR / "floors.geojson"
PROPERTY_UNITS_FILE = STUDY_AREA_DIR / "property_units.geojson"
UNDERGROUND_FILE = STUDY_AREA_DIR / "underground_assets.geojson"

# Existing 3D outputs
BUILDINGS_3D_FILE = (
    PROJECT_ROOT
    / "data"
    / "outputs"
    / "3d"
    / "buildings_3d.obj"
)

FLOORS_3D_FILE = (
    PROJECT_ROOT
    / "data"
    / "outputs"
    / "3d"
    / "floors_3d.obj"
)

PROPERTY_UNITS_3D_FILE = (
    PROJECT_ROOT
    / "data"
    / "outputs"
    / "3d"
    / "property_units_3d.obj"
)

UNDERGROUND_3D_FILE = (
    PROJECT_ROOT
    / "data"
    / "outputs"
    / "3d"
    / "underground_assets_3d.obj"
)

# Metadata generated by the previous geometry scripts
FLOORS_METADATA_FILE = (
    PROJECT_ROOT
    / "data"
    / "outputs"
    / "3d"
    / "floors_3d_metadata.json"
)

PROPERTY_UNITS_METADATA_FILE = (
    PROJECT_ROOT
    / "data"
    / "outputs"
    / "3d"
    / "property_units_3d_metadata.json"
)

UNDERGROUND_METADATA_FILE = (
    PROJECT_ROOT
    / "data"
    / "outputs"
    / "3d"
    / "underground_assets_3d_metadata.json"
)

# ULPIN registry
ULPIN_REGISTRY_FILE = (
    PROJECT_ROOT
    / "data"
    / "outputs"
    / "identity"
    / "ulpins.json"
)

# Cadastral master model
MASTER_MODEL_FILE = (
    PROJECT_ROOT
    / "data"
    / "outputs"
    / "cadastral"
    / "cadastral_model.json"
)


# ============================================================
# HELPERS
# ============================================================

def ensure_directories() -> None:
    """Create required output directories."""

    GEOJSON_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    MODEL_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )


def require_file(path: Path, description: str) -> None:
    """Fail immediately if an expected source file is missing."""

    if not path.exists():
        raise FileNotFoundError(
            f"Required {description} not found:\n{path}"
        )


def load_geojson(
    path: Path,
    description: str,
) -> gpd.GeoDataFrame:
    """
    Load a GeoJSON dataset and validate its CRS.
    """

    require_file(path, description)

    gdf = gpd.read_file(path)

    if gdf.empty:
        raise ValueError(
            f"{description} is empty:\n{path}"
        )

    if gdf.crs is None:
        raise ValueError(
            f"{description} has no CRS:\n{path}"
        )

    if str(gdf.crs) != EXPECTED_CRS:
        raise ValueError(
            f"{description} has incorrect CRS.\n"
            f"Expected: {EXPECTED_CRS}\n"
            f"Actual:   {gdf.crs}"
        )

    if not gdf.geometry.is_valid.all():
        raise ValueError(
            f"{description} contains invalid geometry."
        )

    return gdf


def export_geojson(
    gdf: gpd.GeoDataFrame,
    filename: str,
) -> Path:
    """
    Export a GeoDataFrame to GeoJSON.

    The source data uses a projected CRS for spatial calculations.
    Web GeoJSON is exported as EPSG:4326 because this is the
    standard geographic CRS expected by most web mapping systems.
    """

    output_path = GEOJSON_DIR / filename

    web_gdf = gdf.to_crs("EPSG:4326")

    web_gdf.to_file(
        output_path,
        driver="GeoJSON",
    )

    return output_path


def copy_if_exists(
    source: Path,
    destination_name: str,
) -> dict[str, Any]:
    """
    Copy an existing 3D model into the web output directory.

    Returns metadata describing whether the model is available.
    """

    destination = MODEL_DIR / destination_name

    if source.exists():
        shutil.copy2(
            source,
            destination,
        )

        return {
            "available": True,
            "file": destination_name,
        }

    return {
        "available": False,
        "file": None,
        "source": str(source),
    }


def load_json_if_exists(
    path: Path,
) -> dict[str, Any] | list[Any] | None:
    """
    Load JSON when available.

    Missing optional metadata does not stop the entire web export.
    """

    if not path.exists():
        return None

    with path.open(
        "r",
        encoding="utf-8",
    ) as file:
        return json.load(file)


def write_json(
    path: Path,
    data: Any,
) -> None:
    """Write formatted JSON."""

    with path.open(
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            data,
            file,
            indent=2,
            ensure_ascii=False,
        )


# ============================================================
# DATASET SUMMARY
# ============================================================

def build_dataset_summary(
    study_area: gpd.GeoDataFrame,
    parcels: gpd.GeoDataFrame,
    buildings: gpd.GeoDataFrame,
    floors: gpd.GeoDataFrame,
    units: gpd.GeoDataFrame,
    underground: gpd.GeoDataFrame,
) -> dict[str, Any]:

    return {
        "study_areas": len(study_area),
        "parcels": len(parcels),
        "buildings": len(buildings),
        "floors": len(floors),
        "property_units": len(units),
        "underground_assets": len(underground),
        "expected_crs": EXPECTED_CRS,
        "web_crs": "EPSG:4326",
    }


# ============================================================
# ENTITY INDEX
# ============================================================

def build_entity_index(
    parcels: gpd.GeoDataFrame,
    buildings: gpd.GeoDataFrame,
    floors: gpd.GeoDataFrame,
    units: gpd.GeoDataFrame,
    underground: gpd.GeoDataFrame,
) -> dict[str, Any]:

    entities: list[dict[str, Any]] = []

    # --------------------------------------------------------
    # PARCELS
    # --------------------------------------------------------

    for _, row in parcels.iterrows():

        parcel_id = str(row["parcel_id"])

        entities.append(
            {
                "entity_type": "PARCEL",
                "entity_id": parcel_id,
                "parent_id": None,
                "display_name": parcel_id,
            }
        )

    # --------------------------------------------------------
    # BUILDINGS
    # --------------------------------------------------------

    for _, row in buildings.iterrows():

        building_id = str(row["building_id"])
        parcel_id = str(row["parcel_id"])

        entities.append(
            {
                "entity_type": "BUILDING",
                "entity_id": building_id,
                "parent_id": parcel_id,
                "display_name": building_id,
            }
        )

    # --------------------------------------------------------
    # FLOORS
    # --------------------------------------------------------

    for _, row in floors.iterrows():

        floor_id = str(row["floor_id"])
        building_id = str(row["building_id"])

        entities.append(
            {
                "entity_type": "FLOOR",
                "entity_id": floor_id,
                "parent_id": building_id,
                "display_name": floor_id,
                "floor_type": str(
                    row.get(
                        "floor_type",
                        "STANDARD",
                    )
                ),
                "z_min": float(row["z_min"]),
                "z_max": float(row["z_max"]),
            }
        )

    # --------------------------------------------------------
    # PROPERTY UNITS
    # --------------------------------------------------------

    for _, row in units.iterrows():

        unit_id = str(row["unit_id"])
        floor_id = str(row["floor_id"])

        entities.append(
            {
                "entity_type": "PROPERTY_UNIT",
                "entity_id": unit_id,
                "parent_id": floor_id,
                "building_id": str(row["building_id"]),
                "z_min": float(row["z_min"]),
                "z_max": float(row["z_max"]),
            }
        )

    # --------------------------------------------------------
    # UNDERGROUND ASSETS
    # --------------------------------------------------------

    for _, row in underground.iterrows():

        asset_id = str(row["asset_id"])
        parcel_id = str(row["parcel_id"])

        entities.append(
            {
                "entity_type": "UNDERGROUND_ASSET",
                "entity_id": asset_id,
                "parent_id": parcel_id,
                "asset_type": str(
                    row.get(
                        "asset_type",
                        "UNKNOWN",
                    )
                ),
                "z_min": float(row["z_min"]),
                "z_max": float(row["z_max"]),
            }
        )

    return {
        "entity_count": len(entities),
        "entities": entities,
    }


# ============================================================
# ULPIN LOOKUP
# ============================================================

def build_ulpin_lookup(
    registry: Any,
) -> dict[str, Any]:

    lookup: dict[str, Any] = {}

    if registry is None:
        return lookup

    records = registry

    if isinstance(registry, dict):

        # Handle common registry structures.
        if "records" in registry:
            records = registry["records"]

        elif "ulpins" in registry:
            records = registry["ulpins"]

        elif "items" in registry:
            records = registry["items"]

    if not isinstance(records, list):
        return lookup

    for record in records:

        if not isinstance(record, dict):
            continue

        ulpin = record.get("ulpin")

        if not ulpin:
            continue

        lookup[str(ulpin)] = record

    return lookup


# ============================================================
# MAIN WEB PREPARATION
# ============================================================

def main() -> None:

    print("=" * 78)
    print("3D ULPIN WEB DATA PREPARATION")
    print("=" * 78)
    print()

    print(f"Project root: {PROJECT_ROOT}")
    print(f"Source CRS:   {EXPECTED_CRS}")
    print("Web CRS:      EPSG:4326")
    print()

    ensure_directories()

    # --------------------------------------------------------
    # LOAD SOURCE DATA
    # --------------------------------------------------------

    print("=" * 78)
    print("LOADING SOURCE DATA")
    print("=" * 78)

    study_area = load_geojson(
        STUDY_AREA_FILE,
        "study area",
    )

    parcels = load_geojson(
        PARCELS_FILE,
        "parcels",
    )

    buildings = load_geojson(
        BUILDINGS_FILE,
        "buildings",
    )

    floors = load_geojson(
        FLOORS_FILE,
        "floors",
    )

    units = load_geojson(
        PROPERTY_UNITS_FILE,
        "property units",
    )

    underground = load_geojson(
        UNDERGROUND_FILE,
        "underground assets",
    )

    print(f"Study areas:         {len(study_area)}")
    print(f"Parcels:              {len(parcels)}")
    print(f"Buildings:            {len(buildings)}")
    print(f"Floors:               {len(floors)}")
    print(f"Property units:       {len(units)}")
    print(f"Underground assets:   {len(underground)}")
    print()

    # --------------------------------------------------------
    # EXPORT GEOJSON
    # --------------------------------------------------------

    print("=" * 78)
    print("EXPORTING WEB GEOJSON")
    print("=" * 78)

    exported_geojson: dict[str, str] = {}

    exported_geojson["study_area"] = str(
        export_geojson(
            study_area,
            "study_area.geojson",
        )
    )

    exported_geojson["parcels"] = str(
        export_geojson(
            parcels,
            "parcels.geojson",
        )
    )

    exported_geojson["buildings"] = str(
        export_geojson(
            buildings,
            "buildings.geojson",
        )
    )

    exported_geojson["floors"] = str(
        export_geojson(
            floors,
            "floors.geojson",
        )
    )

    exported_geojson["property_units"] = str(
        export_geojson(
            units,
            "property_units.geojson",
        )
    )

    exported_geojson["underground_assets"] = str(
        export_geojson(
            underground,
            "underground_assets.geojson",
        )
    )

    for name, path in exported_geojson.items():

        print(
            f"{name:<22} → {path}"
        )

    print()

    # --------------------------------------------------------
    # COPY 3D MODELS
    # --------------------------------------------------------

    print("=" * 78)
    print("PREPARING 3D MODELS")
    print("=" * 78)

    models: dict[str, Any] = {}

    models["buildings"] = copy_if_exists(
        BUILDINGS_3D_FILE,
        "buildings_3d.obj",
    )

    models["floors"] = copy_if_exists(
        FLOORS_3D_FILE,
        "floors_3d.obj",
    )

    models["property_units"] = copy_if_exists(
        PROPERTY_UNITS_3D_FILE,
        "property_units_3d.obj",
    )

    models["underground_assets"] = copy_if_exists(
        UNDERGROUND_3D_FILE,
        "underground_assets_3d.obj",
    )

    for name, info in models.items():

        if info["available"]:
            print(
                f"{name:<22} → AVAILABLE"
            )
        else:
            print(
                f"{name:<22} → NOT AVAILABLE"
            )

    print()

    # --------------------------------------------------------
    # LOAD EXISTING METADATA
    # --------------------------------------------------------

    model_metadata = {

        "floors": load_json_if_exists(
            FLOORS_METADATA_FILE
        ),

        "property_units": load_json_if_exists(
            PROPERTY_UNITS_METADATA_FILE
        ),

        "underground_assets": load_json_if_exists(
            UNDERGROUND_METADATA_FILE
        ),
    }

    # --------------------------------------------------------
    # LOAD ULPIN REGISTRY
    # --------------------------------------------------------

    ulpin_registry = load_json_if_exists(
        ULPIN_REGISTRY_FILE
    )

    ulpin_lookup = build_ulpin_lookup(
        ulpin_registry
    )

    # --------------------------------------------------------
    # LOAD MASTER MODEL
    # --------------------------------------------------------

    master_model_available = (
        MASTER_MODEL_FILE.exists()
    )

    # --------------------------------------------------------
    # BUILD ENTITY INDEX
    # --------------------------------------------------------

    print("=" * 78)
    print("BUILDING ENTITY INDEX")
    print("=" * 78)

    entity_index = build_entity_index(
        parcels,
        buildings,
        floors,
        units,
        underground,
    )

    print(
        f"Indexed entities: {entity_index['entity_count']}"
    )

    print()

    # --------------------------------------------------------
    # BUILD DATASET SUMMARY
    # --------------------------------------------------------

    dataset_summary = build_dataset_summary(
        study_area,
        parcels,
        buildings,
        floors,
        units,
        underground,
    )

    # --------------------------------------------------------
    # WEB MANIFEST
    # --------------------------------------------------------

    web_manifest = {

        "project": {
            "name": "3D ULPIN Prototype",
            "version": "0.1.0",
            "status": "prototype",
            "ulpin_schema": "proposed",
        },

        "coordinate_reference_system": {
            "source": EXPECTED_CRS,
            "web": "EPSG:4326",
            "note": (
                "Source spatial processing uses a projected CRS. "
                "Web GeoJSON is exported to EPSG:4326."
            ),
        },

        "dataset": dataset_summary,

        "layers": {

            "study_area": {
                "type": "GeoJSON",
                "file": "geojson/study_area.geojson",
            },

            "parcels": {
                "type": "GeoJSON",
                "file": "geojson/parcels.geojson",
            },

            "buildings": {
                "type": "GeoJSON",
                "file": "geojson/buildings.geojson",
            },

            "floors": {
                "type": "GeoJSON",
                "file": "geojson/floors.geojson",
            },

            "property_units": {
                "type": "GeoJSON",
                "file": "geojson/property_units.geojson",
            },

            "underground_assets": {
                "type": "GeoJSON",
                "file": "geojson/underground_assets.geojson",
            },
        },

        "models": models,

        "metadata": {
            "floors": (
                "3d/floors_3d_metadata.json"
                if model_metadata["floors"] is not None
                else None
            ),

            "property_units": (
                "3d/property_units_3d_metadata.json"
                if model_metadata["property_units"] is not None
                else None
            ),

            "underground_assets": (
                "3d/underground_assets_3d_metadata.json"
                if model_metadata["underground_assets"] is not None
                else None
            ),
        },

        "identity": {
            "ulpin_registry": (
                "identity/ulpins.json"
                if ulpin_registry is not None
                else None
            ),

            "ulpin_count": len(
                ulpin_lookup
            ),
        },

        "hierarchy": {
            "study_area": "PARCEL",
            "parcel": "BUILDING",
            "building": "FLOOR",
            "floor": "PROPERTY_UNIT",
            "parcel_underground_branch": "UNDERGROUND_ASSET",
        },

        "backend_ready": {
            "master_model_available": master_model_available,
            "api_expected": True,
            "frontend_should_not_access_database": True,
        },
    }

    # --------------------------------------------------------
    # WRITE ENTITY INDEX
    # --------------------------------------------------------

    entity_index_path = (
        OUTPUT_DIR / "entity_index.json"
    )

    write_json(
        entity_index_path,
        entity_index,
    )

    # --------------------------------------------------------
    # WRITE ULPIN LOOKUP
    # --------------------------------------------------------

    ulpin_lookup_path = (
        OUTPUT_DIR / "ulpin_lookup.json"
    )

    write_json(
        ulpin_lookup_path,
        ulpin_lookup,
    )

    # --------------------------------------------------------
    # WRITE MANIFEST
    # --------------------------------------------------------

    manifest_path = (
        OUTPUT_DIR / "web_manifest.json"
    )

    write_json(
        manifest_path,
        web_manifest,
    )

    # --------------------------------------------------------
    # WRITE SUMMARY
    # --------------------------------------------------------

    summary = {

        "status": "PASSED",

        "dataset": dataset_summary,

        "geojson_exports": len(
            exported_geojson
        ),

        "3d_models": {
            name: info["available"]
            for name, info in models.items()
        },

        "ulpins": len(
            ulpin_lookup
        ),

        "entities": entity_index[
            "entity_count"
        ],

        "master_model_available":
            master_model_available,

        "outputs": {
            "manifest": str(
                manifest_path
            ),

            "entity_index": str(
                entity_index_path
            ),

            "ulpin_lookup": str(
                ulpin_lookup_path
            ),
        },
    }

    summary_path = (
        OUTPUT_DIR / "web_export_summary.json"
    )

    write_json(
        summary_path,
        summary,
    )

    # --------------------------------------------------------
    # FINAL VALIDATION
    # --------------------------------------------------------

    print("=" * 78)
    print("WEB EXPORT VALIDATION")
    print("=" * 78)

    required_outputs = [

        manifest_path,

        entity_index_path,

        ulpin_lookup_path,

        summary_path,

        GEOJSON_DIR / "study_area.geojson",

        GEOJSON_DIR / "parcels.geojson",

        GEOJSON_DIR / "buildings.geojson",

        GEOJSON_DIR / "floors.geojson",

        GEOJSON_DIR / "property_units.geojson",

        GEOJSON_DIR / "underground_assets.geojson",
    ]

    failed_outputs = []

    for path in required_outputs:

        if path.exists():

            print(
                f"{str(path.relative_to(OUTPUT_DIR)):<55}"
                "PASSED"
            )

        else:

            failed_outputs.append(path)

            print(
                f"{str(path.relative_to(OUTPUT_DIR)):<55}"
                "FAILED"
            )

    if failed_outputs:

        raise RuntimeError(
            "Web export validation failed."
        )

    # --------------------------------------------------------
    # FINAL SUMMARY
    # --------------------------------------------------------

    print()
    print("=" * 78)
    print("3D ULPIN WEB DATA PREPARATION COMPLETE")
    print("=" * 78)
    print()

    print(
        f"GeoJSON layers:       {len(exported_geojson)}"
    )

    print(
        f"Indexed entities:     {entity_index['entity_count']}"
    )

    print(
        f"ULPIN records:        {len(ulpin_lookup)}"
    )

    print(
        f"Master model:         "
        f"{'AVAILABLE' if master_model_available else 'NOT FOUND'}"
    )

    print()

    print(
        f"Web output:           {OUTPUT_DIR}"
    )

    print(
        f"Manifest:             {manifest_path}"
    )

    print(
        f"Entity index:         {entity_index_path}"
    )

    print(
        f"ULPIN lookup:         {ulpin_lookup_path}"
    )

    print()

    print("=" * 78)
    print("ALL WEB EXPORT VALIDATIONS PASSED")
    print("=" * 78)


if __name__ == "__main__":
    main()